spring.application.name=BEZMA
spring.config.import=optional:file:.env[.properties]

# Jackson & Session
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.serialization.fail-on-empty-beans=false
server.servlet.session.cookie.max-age=604800

# Mail (Dùng chung host, port - User/Pass l?y t? .env)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT & Redis (L?y t? .env)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPRIRATION_DEV}
jwt.refresh-expiration = ${JWT_EXPRIRATION_DEV}
spring.data.redis.url=${REDIS_URL}

# App URL linh ho?t
app.base-url=${APP_BASE_URL}
app.frontend-url=${APP_FRONTEND_URL}